lesson3
MaxiNCh/GB_JS_advanced pull request #3
Opened 2020-10-18 22:03 UTC by MaxiNCh

Lesson3

2020-10-22 14:38 UTC, Om1X requested changes
Нужна доработка корзины

2020-10-22 14:38 UTC, Om1X commented on lesson3/project/js/main.js
> +    const products = list.allProducts;
так мы жестко привязываемся к конкретной переменной list, что не есть хорошо, т.к. эта переменная может быть любой, поэтому лучше каталог / корзину лучше передавать через параметры.

2020-10-25 17:03 UTC, MaxiNCh commented on lesson3/project/js/main.js
> +    const products = list.allProducts;
Скорректировал данный код. Каталог передается через параметры.

2020-10-29 11:53 UTC, Om1X approved these changes

2020-10-29 11:53 UTC, Om1X commented on lesson3/project/js/main.js
> +    }
проверка тут лишняя

2020-10-29 18:51 UTC, merged